# Generated by Django 4.2.4 on 2023-08-26 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('name', models.CharField(max_length=550)),
                ('username', models.CharField(max_length=550)),
                ('picture', models.CharField(blank=True, max_length=550, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='users.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching', to='users.profile')),
                ('watching_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='users.profile')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user_id'], name='users_userw_user_id_730527_idx'), models.Index(fields=['watching_user_id'], name='users_userw_watchin_79f5a1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userwatching',
            constraint=models.UniqueConstraint(fields=('user_id', 'watching_user_id'), name='unique_watchers'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username'], name='users_profi_usernam_61311f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user_id'], name='users_profi_user_id_783607_idx'),
        ),
    ]
