# Generated by Django 4.2.4 on 2023-08-17 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
