# Generated by Django 4.2.4 on 2023-08-18 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(default=uuid.uuid4),
        ),
    ]
